image: node:12

stages:
  - build
  - test

before_script:
  - npm install

cache:
  paths:
    - node_modules/

Lint Changes:
  stage: test
  script:
    - npm run lint
    - npx tsc
  only:
    - merge_requests
