image: node:12

stages:
  - build
  - test
  - deploy

before_script:
  - npm install
  - cat $NPM_CREDENTIAL > ~/.npmrc

cache:
  paths:
    - node_modules/

Lint Changes:
  stage: test
  script:
    - npm run lint
    - npx tsc
  only:
    - merge_requests

Release on NPM:
  stage: deploy
  environment:
    name: production
  script:
    - npm run build:production
    - npm publish --access public
  only:
    - tags
