image: timbru31/node-chrome:hydrogen-slim

stages:
  - build
  - test
  - deploy

before_script:
  - npm install
  - cat $NPM_CREDENTIAL > ~/.npmrc

cache:
  paths:
    - node_modules/

Lint Changes:
  stage: test
  script:
    - npm run lint
    - npx tsc
    - npm run build:production
    - npm run test:ci
  only:
    - merge_requests

Release on NPM:
  stage: deploy
  environment:
    name: production
  script:
    - npm publish --access public
    - |
      curl -L -X POST 'http://purge.jsdelivr.net/' \
      -H 'Cache-Control: no-cache' \
      -H 'Content-Type: application/json' \
      -d '{"path": [
        "/npm/@letscooee/web-sdk/dist/sdk.min.js",
        "/npm/@letscooee/web-sdk@latest/dist/sdk.min.js",
        "/npm/@letscooee/web-sdk/dist/sdk-preview.min.js",
        "/npm/@letscooee/web-sdk@latest/dist/sdk-preview.min.js"
      ]}'
  only:
    - tags
